sudo: false
language: ruby
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.6
  - 2.7.1

before_install:
  - gem install bundler

before_script:
  - cp .env.test .env

script:
  - bundle exec rspec spec/

notifications:
  email:
    - christian@minimul.com
