sudo: false
language: ruby
rvm:
  - 2.6.8
  - 2.7.4
  - 3.0.2

before_install:
  - gem install bundler

before_script:
  - cp .env.test .env

script:
  - bundle exec rspec spec/

notifications:
  email:
    - christian@minimul.com
